# Generated by Django 5.1.3 on 2024-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0002_alter_profile_github_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=39, null=True, unique=True),
        ),
    ]
