# Generated by Django 5.1.3 on 2024-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0003_alter_profile_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spark_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
