# Generated by Django 5.1.3 on 2024-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0008_alter_sparkproject_members_alter_sparkproject_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparkproject',
            name='miro_board_link',
        ),
        migrations.AddField(
            model_name='sparkproject',
            name='miro_board_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
