# Generated by Django 5.1.3 on 2024-12-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0010_alter_sparkproject_miro_board_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparkproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sparkproject',
            name='updated_at',
        ),
    ]
