# Generated by Django 5.1.3 on 2024-12-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0011_remove_sparkproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkproject',
            name='github_project_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
