steps:
# Step 1: Build, Push, and Deploy Superhero Services (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superheroes" ]; then
        for superhero in $(ls ./superheroes); do
          if [ -d "./superheroes/$superhero" ]; then
            # Derive service account name based on superhero folder name
            service_account="${superhero}@${_PROJECT_ID}.iam.gserviceaccount.com"
            echo "Binding IAM policy for $superhero to allow unauthenticated access..."
            gcloud run services add-iam-policy-binding $superhero \
              --region=europe-west1 \
              --member=allUsers \
              --role=roles/run.invoker \
              --platform=managed \
              --service-account=$service_account
          else
            echo "Directory './superheroes/$superhero' not found, skipping IAM policy binding for $superhero."
          fi
        done
      else
        echo "Directory './superheroes' not found, skipping IAM policy binding."
      fi

# Step 2: Build, Push, Deploy, and Bind IAM Policy for Superhero Services
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        if [ -d "./superheroes" ]; then
          for superhero in $(ls ./superheroes); do
            if [ -d "./superheroes/$superhero" ]; then
              # Derive service account name based on superhero folder name
              service_account="${superhero}@${_PROJECT_ID}.iam.gserviceaccount.com"

              # Build Docker image with no cache
              echo "Building Docker image for $superhero..."
              docker build --no-cache -t gcr.io/${_PROJECT_ID}/$superhero:latest ./superheroes/$superhero
              docker push gcr.io/${_PROJECT_ID}/$superhero:latest

              # Deploy to Cloud Run and bind IAM policy
              echo "Deploying $superhero to Cloud Run..."
              gcloud run deploy $superhero \
                --image=gcr.io/${_PROJECT_ID}/$superhero:latest \
                --region=europe-west1 \
                --platform=managed \
                --allow-unauthenticated \
                --service-account=$service_account \
                --timeout=900s

              # Binding IAM policy to allow unauthenticated access
              echo "Binding IAM policy for $superhero to allow unauthenticated access..."
              gcloud run services add-iam-policy-binding $superhero \
                --region=europe-west1 \
                --member=allUsers \
                --role=roles/run.invoker \
                --platform=managed \
                --service-account=$service_account
            else
              echo "Directory './superheroes/$superhero' not found, skipping $superhero."
            fi
          done
        else
          echo "Directory './superheroes' not found, skipping superhero services deployment."
        fi


# Step 3: IAM Policy Binding for Superhero Services (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superheroes" ]; then
        for superhero in $(ls ./superheroes); do
          if [ -d "./superheroes/$superhero" ]; then
            echo "Binding IAM policy for $superhero to allow unauthenticated access..."
            gcloud beta run services add-iam-policy-binding $superhero \
              --region=europe-west1 \
              --member=allUsers \
              --role=roles/run.invoker \
              --platform=managed \
              --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com
          else
            echo "Directory './superheroes/$superhero' not found, skipping IAM policy binding for $superhero."
          fi
        done
      else
        echo "Directory './superheroes' not found, skipping IAM policy binding."
      fi

# Step 4: Build, Push, and Deploy Avengers Backend (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./avengers/backend/" ]; then
        echo "Building Avengers backend..."
        # Build Docker image with no cache
        docker build --no-cache -t gcr.io/${_PROJECT_ID}/avengers-backend:latest ./avengers/backend/
        docker push gcr.io/${_PROJECT_ID}/avengers-backend:latest

        echo "Deploying Avengers backend to Cloud Run..."
        # Deploy the image to Cloud Run
        gcloud run deploy avengers-backend \
          --image=gcr.io/${_PROJECT_ID}/avengers-backend:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com \
          --timeout=900s  # Increase timeout to 15 minutes

        echo "Binding IAM policy for Avengers backend to allow unauthenticated access..."
        # Bind IAM policy to allow unauthenticated access
        gcloud run services add-iam-policy-binding avengers-backend \
          --region=europe-west1 \
          --member=allUsers \
          --role=roles/run.invoker \
          --platform=managed \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com
      else
        echo "Directory './avengers/backend/' not found, skipping Avengers backend deployment."
      fi


# Step 5: Build, Push, and Deploy X-Men Backend (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./x-men/backend/" ]; then
        echo "Building X-Men backend..."
        docker build --no-cache -t gcr.io/${_PROJECT_ID}/xmen-backend:latest ./x-men/backend/
        docker push gcr.io/${_PROJECT_ID}/xmen-backend:latest
        gcloud run deploy xmen-backend \
          --image=gcr.io/${_PROJECT_ID}/xmen-backend:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com \
          --timeout=900s  # Increase timeout to 15 minutes
      else
        echo "Directory './x-men/backend/' not found, skipping X-Men backend deployment."
      fi

# Step 6: Build, Push, and Deploy X-Men Frontend (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./x-men/frontend/" ]; then
        echo "Building X-Men frontend..."
        docker build --no-cache -t gcr.io/${_PROJECT_ID}/xmen-frontend:latest ./x-men/frontend/
        docker push gcr.io/${_PROJECT_ID}/xmen-frontend:latest
        gcloud run deploy xmen-frontend \
          --image=gcr.io/${_PROJECT_ID}/xmen-frontend:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com \
          --timeout=900s  # Increase timeout to 15 minutes
      else
        echo "Directory './x-men/frontend/' not found, skipping X-Men frontend deployment."
      fi

# Step 7: Build, Push, and Deploy Jarvis Backend (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./jarvis/" ]; then
        echo "Building and deploying Jarvis backend..."
        docker build --no-cache -t gcr.io/${_PROJECT_ID}/jarvis:latest ./jarvis/
        docker push gcr.io/${_PROJECT_ID}/jarvis:latest
        gcloud run deploy jarvis \
          --image=gcr.io/${_PROJECT_ID}/jarvis:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com \
          --timeout=900s
      else
        echo "Directory './jarvis/' not found, skipping build and deployment for Jarvis."
      fi

# Specify logging behavior to satisfy requirements
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs

# Define Substitutions
substitutions:
  _PROJECT_ID: 'hero-alliance-feup-ds-24-25'

timeout: 1800s
