steps:
# Step 1: Build, Push, and Deploy Superhero Services
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Building, pushing, and deploying superhero services..."

      docker build -t gcr.io/hero-alliance-feup-ds-24-25/superhero-1-1:latest ./superhero-services/
      docker push gcr.io/hero-alliance-feup-ds-24-25/superhero-1-1:latest
      gcloud run deploy superhero-1-1 \
        --image=gcr.io/hero-alliance-feup-ds-24-25/superhero-1-1:latest \
        --region=europe-west1 \
        --platform=managed \
        --allow-unauthenticated \
        --service-account=superhero-1-1@hero-alliance-feup-ds-24-25.iam.gserviceaccount.com

      docker build -t gcr.io/hero-alliance-feup-ds-24-25/superhero-1-2:latest ./superhero-services/
      docker push gcr.io/hero-alliance-feup-ds-24-25/superhero-1-2:latest
      gcloud run deploy superhero-1-2 \
        --image=gcr.io/hero-alliance-feup-ds-24-25/superhero-1-2:latest \
        --region=europe-west1 \
        --platform=managed \
        --allow-unauthenticated \
        --service-account=superhero-1-2@hero-alliance-feup-ds-24-25.iam.gserviceaccount.com

      # Repeat the above block for each superhero (1-1 to 8-5).

# Step 2: Build, Push, and Deploy Avengers Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/hero-alliance-feup-ds-24-25/avengers-backend:latest'
    - './backend/avengers/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/hero-alliance-feup-ds-24-25/avengers-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'avengers-backend'
    - '--image=gcr.io/hero-alliance-feup-ds-24-25/avengers-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-8-5@hero-alliance-feup-ds-24-25.iam.gserviceaccount.com'

# Step 3: Build, Push, and Deploy X-Men Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/hero-alliance-feup-ds-24-25/xmen-backend:latest'
    - './backend/xmen/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/hero-alliance-feup-ds-24-25/xmen-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'xmen-backend'
    - '--image=gcr.io/hero-alliance-feup-ds-24-25/xmen-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-8-5@hero-alliance-feup-ds-24-25.iam.gserviceaccount.com'

# Step 4: Build, Push, and Deploy Jarvis Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/hero-alliance-feup-ds-24-25/jarvis:latest'
    - './backend/jarvis/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/hero-alliance-feup-ds-24-25/jarvis:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'jarvis'
    - '--image=gcr.io/hero-alliance-feup-ds-24-25/jarvis:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-8-5@hero-alliance-feup-ds-24-25.iam.gserviceaccount.com'

# Specify logging behavior to satisfy requirements
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs

timeout: 1800s
