- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./jarvis/" ]; then
        echo "Building and deploying Jarvis backend..."
        docker build -t gcr.io/${_PROJECT_ID}/jarvis:latest ./jarvis/
        docker push gcr.io/${_PROJECT_ID}/jarvis:latest
        gcloud run deploy jarvis \
          --image=gcr.io/${_PROJECT_ID}/jarvis:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com \
          --timeout=900s
      else
        echo "Directory './jarvis/' not found, skipping build and deployment for Jarvis."
      fi
