steps:
# Step 1: Build, Push, and Deploy Superhero Services
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Define superhero services
      for i in {1..8}; do
        for j in {1..5}; do
          SERVICE="superhero-${_PROJECT_ID}-${i}-${j}"
          IMAGE="gcr.io/${_PROJECT_ID}/${SERVICE}:latest"
          SERVICE_ACCOUNT="${SERVICE}@${_PROJECT_ID}.iam.gserviceaccount.com"

          echo "Building image for $SERVICE..."
          docker build -t $IMAGE ./superhero-services/

          echo "Pushing image for $SERVICE..."
          docker push $IMAGE

          echo "Deploying $SERVICE to Cloud Run..."
          gcloud run deploy $SERVICE \
            --image=$IMAGE \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=$SERVICE_ACCOUNT
        done
      done

# Step 2: Build, Push, and Deploy Avengers Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/avengers-backend:latest'
    - './backend/avengers/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/avengers-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'avengers-backend-${_PROJECT_ID}'
    - '--image=gcr.io/${_PROJECT_ID}/avengers-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-01-01@${_PROJECT_ID}.iam.gserviceaccount.com'

# Step 3: Build, Push, and Deploy X-Men Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/xmen-backend:latest'
    - './backend/xmen/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/xmen-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'xmen-backend-${_PROJECT_ID}'
    - '--image=gcr.io/${_PROJECT_ID}/xmen-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-01-01@${_PROJECT_ID}.iam.gserviceaccount.com'

# Step 4: Build, Push, and Deploy Jarvis Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/jarvis:latest'
    - './backend/jarvis/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/jarvis:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'jarvis-${_PROJECT_ID}'
    - '--image=gcr.io/${_PROJECT_ID}/jarvis:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-01-01@${_PROJECT_ID}.iam.gserviceaccount.com'

# Step 5: Deploy Avengers Frontend to Storage Bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-r'
    - './frontend/avengers'
    - 'gs://avengers-frontend-${_PROJECT_ID}'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'storage'
    - 'buckets'
    - 'update'
    - 'gs://avengers-frontend-${_PROJECT_ID}'
    - '--public-access'

# Define Substitutions
substitutions:
  _PROJECT_ID: 'hero-alliance-feup-ds-24-25'

timeout: 1800s
