steps:
# Step 1: Build, Push, and Deploy Superhero Services (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superhero-services" ]; then
        for i in {1..8}; do
          for j in {1..5}; do
            echo "Building image for superhero-${i}-${j}..."
            # Ensure the correct relative path for superhero-services
            docker build -t gcr.io/${_PROJECT_ID}/superhero-${i}-${j}:latest ./superhero-services/

            echo "Pushing image for superhero-${i}-${j}..."
            docker push gcr.io/${_PROJECT_ID}/superhero-${i}-${j}:latest
          done
        done
      else
        echo "Directory './superhero-services' not found, skipping superhero services build."
      fi

# Step 2: Deploy Superhero Services using gcloud (moved to separate step)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superhero-services" ]; then
        for i in {1..8}; do
          for j in {1..5}; do
            echo "Deploying superhero-${i}-${j} to Cloud Run..."
            gcloud run deploy superhero-${i}-${j} \
              --image=gcr.io/${_PROJECT_ID}/superhero-${i}-${j}:latest \
              --region=europe-west1 \
              --platform=managed \
              --allow-unauthenticated \
              --service-account=superhero-${i}-${j}@${_PROJECT_ID}.iam.gserviceaccount.com
          done
        done
      else
        echo "Directory './superhero-services' not found, skipping superhero services deployment."
      fi

# Diagnostic step.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'version'

# Step 3: Build, Push, and Deploy Avengers Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/avengers-backend:latest'
    - './backend/avengers/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/avengers-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'avengers-backend'
    - '--image=gcr.io/${_PROJECT_ID}/avengers-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com'

# Step 4: Build, Push, and Deploy X-Men Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/xmen-backend:latest'
    - './backend/xmen/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/xmen-backend:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'xmen-backend'
    - '--image=gcr.io/${_PROJECT_ID}/xmen-backend:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com'

# Step 5: Build, Push, and Deploy Jarvis Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/jarvis:latest'
    - './backend/jarvis/'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/jarvis:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'jarvis'
    - '--image=gcr.io/${_PROJECT_ID}/jarvis:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=superhero-08-05@${_PROJECT_ID}.iam.gserviceaccount.com'

# Specify logging behavior to satisfy requirements
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs

# Define Substitutions
substitutions:
  _PROJECT_ID: 'hero-alliance-feup-ds-24-25'

timeout: 1800s
