steps:
# Step 1: Build, Push, and Deploy Superhero Services (skip if directory doesn't exist)
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superheroes" ]; then
        for superhero in $(ls ./superheroes); do
          if [ -d "./superheroes/$superhero" ]; then
            echo "Building image for $superhero..."
            docker build -t gcr.io/${_PROJECT_ID}/$superhero:latest ./superheroes/$superhero/
            echo "Pushing image for $superhero..."
            docker push gcr.io/${_PROJECT_ID}/$superhero:latest
          fi
        done
      else
        echo "Directory './superheroes' not found, skipping superhero services build."
      fi

# Step 2: Deploy Superhero Services using gcloud
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superheroes" ]; then
        for superhero in $(ls ./superheroes); do
          if [ -d "./superheroes/$superhero" ]; then
            echo "Deploying $superhero to Cloud Run..."
            gcloud run deploy $superhero \
              --image=gcr.io/${_PROJECT_ID}/$superhero:latest \
              --region=europe-west1 \
              --platform=managed \
              --allow-unauthenticated \
              --service-account=$superhero@${_PROJECT_ID}.iam.gserviceaccount.com
          fi
        done
      else
        echo "Directory './superheroes' not found, skipping superhero services deployment."
      fi

# Step 3: IAM Policy Binding for Superhero Services
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -d "./superheroes" ]; then
        for superhero in $(ls ./superheroes); do
          if [ -d "./superheroes/$superhero" ]; then
            echo "Binding IAM policy for $superhero to allow unauthenticated access..."
            gcloud run services add-iam-policy-binding $superhero \
              --region=europe-west1 \
              --member=allUsers \
              --role=roles/run.invoker \
              --platform=managed
          fi
        done
      else
        echo "Directory './superheroes' not found, skipping IAM policy binding."
      fi

# Diagnostic step.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'version'

# Additional steps for other services (Avengers, X-Men, Jarvis) with similar IAM policy binding

# Specify logging behavior to satisfy requirements
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs

# Define Substitutions
substitutions:
  _PROJECT_ID: 'hero-alliance-feup-ds-24-25'

timeout: 1800s
