# Generated by Django 5.1.2 on 2024-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('response', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField()),
                ('plantuml_code', models.TextField(blank=True, null=True)),
                ('repo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('plantuml_image', models.ImageField(blank=True, null=True, upload_to='plantuml_images/')),
            ],
        ),
    ]
