version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - .:/app       # Mount your project directory into the container for development
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

