# Use Python 3.11 Alpine as a base image
FROM python:3.11-alpine

# Copy the Python script into the container
COPY app.py /app.py

# Expose port 8080 for the app
EXPOSE 8080

# Run the Python app
CMD ["python3", "/app.py"]

