services:
  backend:
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
