services:
  featurecraft:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: t03_g01_featurecraft:latest
    ports:
      - "8080:8080" # Backend
    volumes:
      - .:/app
    environment:
      - NAME=FeatureCraft
      - PYTHONUNBUFFERED=1
      - C3T1_LLM_API_KEY=${C3T1_LLM_API_KEY}
      - C3T1_CORS_URL=${C3T1_CORS_URL}
      - C3T1_DB_COLLECTION=${C3T1_DB_COLLECTION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase.json
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.json:/tmp/swagger.json
    environment:
      - SWAGGER_JSON=/tmp/swagger.json
volumes:
  mongodb_data:
