services:
  featurecraft:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: t03_g01_featurecraft:latest
    ports:
      - "8080:8080" # Backend
    volumes:
      - .:/app
    environment:
      - NAME=FeatureCraft
      - PYTHONUNBUFFERED=1
      - superhero-03-01-secret=${superhero-03-01-secret}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase.json
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.json:/tmp/swagger.json
    environment:
      - SWAGGER_JSON=/tmp/swagger.json
volumes:
  mongodb_data:
