# Generated by Django 5.1.3 on 2024-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0004_profile_spark_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='spark_token',
            new_name='miro_token',
        ),
    ]
