version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-py
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules      